variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - regex

regex:
  stage: regex
  image: "alpine:latest"
  only:
    refs:
      - merge_requests
  script:
    - apk add bash curl jq
    - unagi/ci-scripts/note_regex.sh
